### ISSUE TITLE
 测试了下，还有一点小问题

### ISSUE THREAD

**Issue by biwawa** [ZiBuYuCHN/xiuno_ckeditor#8]
1.图片上传好像没经过xiunophp压缩处理（这应该不算问题）
2.图片没有后缀！
3.上传图片如果尺寸过大，会占满输入框！除了修改图片标题，无法继续输入其他内容（建议markdown-body 做图片大小显示限制）

xiuno那么多编辑器，基本都是半残，只有这个颜值高，相对好用，所以比较关注

**Comment by orziz** [comment]
图片后缀那个为设计方案，并不是bug
